project:
  type: website
  output-dir: docs

lang: zh-CN

website:
  title: "El Psy Kongroo"
  description: "Operation Skuld"
  site-url: "https://christina2cher.github.io/Blog/"

  search: false
  reader-mode: true
  back-to-top-navigation: true

  navbar:
    background: "#17181c"
    pinned: true

  page-footer:
    left: "© El Psy Kongroo"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true

  open-graph: true
  twitter-card: true

  llms-txt: true

format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]

    respect-user-color-scheme: true
    toc: true
    toc-title: "本文大纲"     
    toc-depth: 3  
    toc-expand: 2

    html-math-method: mathjax

    code-fold: true
    code-summary: "展开查看代码" 
    code-line-numbers: true  
    code-copy: true  
    code-overflow: wrap        
    fig-align: center
    fig-cap-location: bottom
    tbl-cap-location: top
    lightbox: true

    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true

    canonical-url: true

execute:
  freeze: auto